services:
  votx_db:
    image: postgres
    container_name: votx_db
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - path: "./db.env"
        required: true
    restart: always
    volumes: 
      - ./db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "votx", "-d", "votx"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - private

  votx:
    container_name: votx
    build: .
    ports:
      - 127.0.0.1:8008:8008
    env_file:
      - path: "./db.env"
        required: true
      - path: "./.env"
        required: true
    restart: always
    depends_on:
      votx_db:
        condition: service_healthy
        restart: true
    networks:
      - public
      - private

networks:
  public:
    name: public_network
    external: true
  private:
    external: false