services:
  postgres:
    image: postgres
    container_name: votix_db
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - path: "./db.env"
        required: true

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password