[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pydocstyle
    "D",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # pep8-naming
    "N"
]
ignore = [
    # prevent function calls in argument defaults --> required in fastAPI
    "B008",
    # ignore missing docstrings
    "D1",
    # incompatibility issues
    "D203",
    "D211",
    "D213"
]

[tool.ruff.lint.pydocstyle]

[tool.ruff]
line-length = 88

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
docstring-code-format = true